spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding:  UTF-8
    cache: false

  jackson:
    time-zone: GMT+8
logging:
  level: 
    root: INFO  # INFO  ERROR DEBUG
server:
  port: 80
  servlet:
    context-path: /outer




                  